const PROJECTS_DATA = [
    {
        id: 6,
        name: 'Ethereum Transfer Dapp',
        desc: 'Ethereum Transfer is a decentralised application built on ethereum blockchain',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318800/5_ocb8zg.jpg',
        tech: [{ class: '/icons/nextjs.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://eth-transfer-dapp.vercel.app/',
        github: 'https://github.com/mukulrajpoot262610/eth-transfer-dapp',
        type: 'WebApp',
        category: 'Personal'
    },
    {
        id: 8,
        name: 'Ethereum Transfer Dapp',
        desc: 'Ethereum Transfer is a decentralised application built on ethereum blockchain',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318800/5_ocb8zg.jpg',
        tech: [{ class: '/icons/nextjs.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://eth-transfer-dapp.vercel.app/',
        github: 'https://github.com/mukulrajpoot262610/eth-transfer-dapp',
        type: 'WebApp',
        category: 'Personal'
    },
    {
        id: 7,
        name: 'Worthpad NFT Place',
        desc: 'Worthpad is an innovative, decentralized, multi-chain DeFi platform that makes investing in DeFi and crypto projects easy and accessible for the masses. Worthpad empowers high growth potential crypto projects with the ability to raise liquidity in a fair manner while also developing dedicated communities behind them.',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318800/5_ocb8zg.jpg',
        tech: [{ class: '/icons/nextjs.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://www.worthpad.org/',
        github: 'https://github.com/mukulrajpoot262610',
        type: 'WebApp',
        category: 'Freelance'
    },
    {
        id: 1,
        name: 'Dev Community Clone',
        desc: 'Dev Community is Full-stack Blogging Application build with MERN. This project is inspired from dev.to website, I enjoyed and learned a lot while building this. I used React for Front-end User interface, Redux for State Management, Redux thunk for Asynchronous tasks, Express for Backend server, MongoDB Atlas for Database, JSON Web Tokens for Authentications, SHA256 Hashing Algo to hash password and Firbase for storage.',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318796/1_r6odw9.jpg',
        tech: [{ class: '/icons/react.svg', name: 'React' }, { class: '/icons/expressjs.svg', name: 'Express' }, { class: '/icons/mongodb.svg', name: 'MongoDB' }, { class: '/icons/firebase.svg', name: 'Firebase' }],
        date: 'Jun, 2021',
        link: 'http://blog-website-mr.herokuapp.com/',
        github: 'https://github.com/mukulrajpoot262610/Blog-website',
        type: 'WebApp',
    },
    {
        id: 2,
        name: 'adidas Online Store',
        desc: 'adidas Online store is a Full-stack E-commerce Application with SEO compatible via NEXT.js.',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1640495655/Untitled_design_2_malm4g.png',
        tech: [{ class: '/icons/react.svg', name: 'React' }, { class: '/icons/expressjs.svg', name: 'Express' }, { class: '/icons/mongodb.svg', name: 'MongoDB' }],
        date: 'Dec 2021',
        link: 'https://adidas-clone.vercel.app/',
        github: '-',
        type: 'WebApp',
    },
    {
        id: 3,
        name: 'authFlow.io',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318802/3_becmce.png',
        tech: [{ class: '/icons/react.svg', name: 'React' }, { class: '/icons/expressjs.svg', name: 'Express' }, { class: '/icons/mongodb.svg', name: 'MongoDB' }, { class: '/icons/firebase.svg', name: 'Firebase' }],
        date: 'Aug 2021',
        link: 'https://auth-flow.vercel.app/',
        github: 'https://github.com/mukulrajpoot262610/authFlow-social',
        type: 'WebApp & Website',
    },
    {
        id: 4,
        name: 'DEV-profiler',
        desc: 'This is my portfolio website in 2021.',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1637670521/Untitled_design_1_xox2jt.png',
        tech: [{ class: '/icons/nextjs.svg', name: 'NextJS' }, { class: '/icons/vercel.svg', name: 'Vercel' }, { class: '/icons/tailwind.svg', name: 'Tailwind' }],
        date: 'Aug 2021',
        link: 'https://dev-profiler.vercel.app/',
        github: 'https://github.com/mukulrajpoot262610/github_profiler',
        type: 'Website',
    },
    {
        id: 5,
        name: 'TrackIt',
        desc: 'TrackIt is web application by which users can track Covid Cases and Weather on interacting with Map.',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318800/5_ocb8zg.jpg',
        tech: [{ class: '/icons/html5.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://trackit-mr.netlify.app/',
        github: 'https://github.com/mukulrajpoot262610/track-it',
        type: 'WebApp',
    },
]

export default PROJECTS_DATA
