const PROJECTS_DATA = [
    {
        id: 1,
        name: 'Dev Community Clone',
        desc: 'Dev Community is Full-stack Blogging Application build with MERN. This project is inspired from dev.to website, I enjoyed and learned a lot while building this. I used React for Front-end User interface, Redux for State Management, Redux thunk for Asynchronous tasks, Express for Backend server, MongoDB Atlas for Database, JSON Web Tokens for Authentications, SHA256 Hashing Algo to hash password and Firbase for storage.',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318796/1_r6odw9.jpg',
        tech: [{ class: '/icons/react.svg', name: 'React' }, { class: '/icons/expressjs.svg', name: 'Express' }, { class: '/icons/mongodb.svg', name: 'MongoDB' }, { class: '/icons/firebase.svg', name: 'Firebase' }],
        date: 'Jun, 2021',
        link: 'http://blog-website-mr.herokuapp.com/',
        github: 'https://github.com/mukulrajpoot262610/Blog-website',
        type: 'WebApp',
    },
    {
        id: 2,
        name: 'TrackerX',
        desc: 'TrackerX is a Full-stack MERN Application for managing finances. I build this App for personal use, I was not able to find an app for managing finances which can fulfill my needs So, I decided to build my own 😋. User can track their expenses and income with various Filter Options. I used React-Bootstrap to build User Interface, Redux to manage state, Express for Backend API server, MongoDB Atlas as Database.',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318797/2_dw7l5v.jpg',
        tech: [{ class: '/icons/react.svg', name: 'React' }, { class: '/icons/expressjs.svg', name: 'Express' }, { class: '/icons/mongodb.svg', name: 'MongoDB' }],
        date: '--',
        link: '',
        github: 'https://github.com/mukulrajpoot262610/trackerX',
        type: 'WebApp',
    },
    {
        id: 3,
        name: 'dev Friend.io',
        desc: 'devFriend.io is platform where college developers can find their project partner. It provides them a platform to create their online portfolio with with their projects and github data. It is full-stack Web application. It is not completed yet, I am working hard to complete this in my free time.',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318802/3_becmce.png',
        tech: [{ class: '/icons/react.svg', name: 'React' }, { class: '/icons/expressjs.svg', name: 'Express' }, { class: '/icons/mongodb.svg', name: 'MongoDB' }, { class: '/icons/firebase.svg', name: 'Firebase' }],
        date: 'Aug 2021',
        link: 'https://devfriend-socila.vercel.app/',
        github: '',
        type: 'WebApp & Website',
    },
    {
        id: 4,
        name: 'Portfolio-2021',
        desc: 'This is my portfolio website in 2021.',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318807/4_m6or3t.png',
        tech: [{ class: '/icons/nextjs.svg', name: 'NextJS' }, { class: '/icons/gsap.svg', name: 'GSAP' }, { class: '/icons/vercel.svg', name: 'Vercel' }, { class: '/icons/tailwind.svg', name: 'Tailwind' }],
        date: 'Aug 2021',
        link: 'https://mukulrajpoot.vercel.app/',
        github: 'https://github.com/mukulrajpoot262610/portfolio-2021',
        type: 'Website',
    },
    {
        id: 5,
        name: 'TrackIt',
        desc: 'TrackIt is web application by which users can track Covid Cases and Weather on interacting with Map.',
        image: 'https://res.cloudinary.com/mukulrajpoot/image/upload/c_thumb,w_200,g_face/v1632318800/5_ocb8zg.jpg',
        tech: [{ class: '/icons/html5.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://trackit-mr.netlify.app/',
        github: 'https://github.com/mukulrajpoot262610/track-it',
        type: 'WebApp',
    },
]

export default PROJECTS_DATA